services:
  immich-public-proxy:
    container_name: immich-public-proxy
    image: alangrainger/immich-public-proxy:1.4.1
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./config.json:/app/config.json:ro
    labels:
      traefik.enable: true
      traefik.http.routers.immich-proxy.entryPoints: websecure
      traefik.http.services.immich-proxy.loadbalancer.server.port: 3000
      traefik.http.routers.immich-proxy.rule: Host(`public.photos.hoebergen.net`)
    networks:
      - immich
      - frontend

networks:
  frontend:
    external: true
  immich:
    external: true