services:
  prometheus:
    image: prom/prometheus:v3.14.0
    container_name: prometheus
    user: "1000:1000"
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=28d'
      - '--web.enable-remote-write-receiver'
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /docker/prometheus/data:/prometheus
    networks:
      - frontend
    labels:
      traefik.enable: true
      traefik.http.routers.prometheus.rule: Host(`prometheus.str-vps-01.hoebergen.net`)
      traefik.http.routers.prometheus.entryPoints: websecure
      traefik.http.services.prometheus.loadbalancer.server.port: 9090
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    environment:
      - TZ=Europe/Amsterdam

networks:
  frontend:
    external: true

