services:
  outline:
    container_name: outline
    image: docker.getoutline.com/outlinewiki/outline:latest
    env_file: .env
    labels:
      # Traefik
      traefik.enable: true
      traefik.http.routers.outline.entryPoints: websecure
      traefik.http.routers.outline.rule: Host(`wiki.hoebergen.net`)
      traefik.http.services.outline.loadbalancer.server.port: 3000
      # Cloudflare
      dockflare.enable: true
      dockflare.hostname: "wiki.hoebergen.net"
      dockflare.originsrvname: "wiki.hoebergen.net"
      dockflare.service: "https://traefik:443"
      dockflare.access.group: "block-all-except-trusted"
    expose:
      - "3000"
    volumes:
      - /docker/outline/config:/var/lib/outline/data
    depends_on:
      - postgres
      - redis
    networks:
      - backend-outline
      - frontend
    environment:
      - TZ=Europe/Amsterdam
  redis:
    container_name: outline-redis
    image: redis
    env_file: .env
    expose:
      - "6379"
    volumes:
      - /docker/outline/redis/redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3
    networks:
      - backend-outline
    environment:
      - TZ=Europe/Amsterdam
  postgres:
    container_name: outline-postgres
    image: postgres:18
    env_file: .env
    expose:
      - "5432"
    volumes:
      - /docker/outline/database:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "outline", "-U", "user"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_DB: 'outline'
      TZ: Europe/Amsterdam
    networks:
      - backend-outline


networks:
  frontend:
    external: true
  backend-outline:
