services:
  immich-public-proxy:
    container_name: immich-public-proxy
    image: alangrainger/immich-public-proxy:3.2.1
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./config.json:/app/config.json:ro
    ports:
      - 3000:3000
    labels:
      # Traefik
      traefik.enable: true
      traefik.http.routers.immich-proxy.entryPoints: websecure
      traefik.http.services.immich-proxy.loadbalancer.server.port: 3000
      traefik.http.routers.immich-proxy.rule: Host(`img.hoebergen.net`)
      # Cloudflare
      dockflare.enable: true
      dockflare.hostname: "img.hoebergen.net"
      dockflare.originsrvname: "img.hoebergen.net"
      dockflare.service: "https://traefik:443"
    networks:
      - immich
      - frontend

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    environment:
      - TZ=Europe/Amsterdam
networks:
  frontend:
    external: true
  immich:
    name: backend-immich
    external: true
