services:
  watchtower:
    container_name: watchtower
    hostname: watchtower.lab-vps-03
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Amsterdam
      - WATCHTOWER_DEBUG=false
      - WATCHTOWER_SCHEDULE=0 0 4 * * ?
      - WATCHTOWER_MONITOR_ONLY=true
      - WATCHTOWER_NOTIFICATION_URL=${WATCHTOWER_NOTIFICATION_URL}
    networks:
      - proxy

networks:
  proxy:
    name: proxy
    external: true

