services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:v0.8.12-slim
    labels:
      traefik.enable: true
      traefik.http.routers.open-webui.entryPoints: websecure
      traefik.http.services.open-webui.loadbalancer.server.port: 8080
      traefik.http.routers.open-webui.rule: Host(`chat.hoebergen.net`)
    volumes:
      - /docker/open-webui/data:/app/backend/data
    environment:
      ENABLE_FORWARD_USER_INFO_HEADERS: true
    env_file:
      - .env
    networks:
      - frontend

networks:
  frontend:
    name: frontend
    external: true