services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main-slim
    labels:
      traefik.enable: true
      traefik.http.routers.open-webui.entryPoints: websecure
      traefik.http.services.open-webui.loadbalancer.server.port: 8080
      traefik.http.routers.open-webui.rule: Host(`chat.hoebergen.net`)
    volumes:
      - /docker/open-webui/data:/app/backend/data
    networks:
      - frontend

networks:
  frontend:
    name: frontend
    external: true