services:
  tplink-api:
    container_name: tplink-api
    image: ghcr.io/jordyegnl/tplink-sg108e-led-api:latest
    environment:
      TP_LINK_IP: 10.0.0.11
      TP_LINK_USERNAME: admin
      TP_LINK_PASSWORD: ${PASSWORD}
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.tplink-api.entryPoints: websecure
      traefik.http.services.tplink-api.loadbalancer.server.port: 5000
      traefik.http.routers.tplink-api.rule: Host(`tplinkapi.hoebergen.net`)
      traefik.http.routers.tplink-api.middlewares: localAccess@file

networks:
  default:
    name: frontend
    external: true
