services:
  uptime-kuma:
    image: louislam/uptime-kuma:2.0.0-beta.2
    container_name: uptime-kuma
    volumes:
      - /home/jordy/docker/uptime-kuma/data:/app/data
    restart: always
    labels:
      traefik.enable: true
      traefik.http.routers.uptime-kuma.entryPoints: https
      traefik.http.services.uptime-kuma.loadbalancer.server.port: 3001
      traefik.http.routers.uptime-kuma.rule: Host(`status.hoebergen.net`)

networks:
  default:
    name: proxy
    external: true
