services:
  termix:
    image: ghcr.io/lukegus/termix:release-2.1.0
    container_name: termix-server
    restart: unless-stopped
    environment:
      PORT: "8080"
    env_file:
      - .env
    volumes:
      - /docker/termix/data:/app/data
    labels:
      # Traefik
      traefik.enable: true
      traefik.http.routers.termix.entryPoints: websecure
      traefik.http.services.termix.loadbalancer.server.port: 8080
      traefik.http.routers.termix.rule: Host(`termix.hoebergen.net`)
      traefik.http.routers.termix.middlewares: localAccess@file
    depends_on:
      - guacd
    networks:
      - termix-backend
      - frontend

  guacd:
    image: guacamole/guacd:latest
    container_name: termix-guacd
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - termix-backend

networks:
  termix-backend:
  frontend:
    name: frontend
    external: true