services:
  termix:
    image: ghcr.io/lukegus/termix:latest
    container_name: termix-server
    restart: unless-stopped
    environment:
      PORT: "8080"
    volumes:
      - /docker/termix/data:/app/data
    depends_on:
      - guacd
    networks:
      - termix-backend
      - pangolin

  guacd:
    image: guacamole/guacd:latest
    container_name: termix-guacd
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - termix-backend

networks:
  termix-backend:
  pangolin:
    name: pangolin
    external: true