version: '3.3'
services:
  stirling-pdf:
    image: ghcr.io/stirling-tools/s-pdf:0.45.5
    container_name: stirling
    restart: unless-stopped
    volumes:
      - ./data:/usr/share/tesseract-ocr/4.00/tessdata
      - ./data/config:/configs
    environment:
      APP_HOME_NAME: Stirling PDF
      APP_HOME_DESCRIPTION: Your locally hosted one-stop-shop for all your PDF needs.
      APP_NAVBAR_NAME: Stirling PDF
      APP_ROOT_PATH: /
      ALLOW_GOOGLE_VISABILITY: false
    labels:
      traefik.enable: true
      traefik.http.routers.stirling.entryPoints: websecure
      traefik.http.routers.stirling.rule: Host(`pdf.hoebergen.net`)

networks:
  default:
    name: frontend
    external: true
