services:
  speedtest-tracker:
    container_name: speedtest-tracker
    image: lscr.io/linuxserver/speedtest-tracker:0.25.0
    environment:
      - PUID=1000
      - PGID=1000
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=speedtest_tracker
      - DB_USERNAME=jordy
      - DB_PASSWORD=${DB_PASSWORD}
      - TZ=Europe/Amsterdam
      - APP_KEY=${APP_KEY}
      - SPEEDTEST_SCHEDULE="0 */6 * * *"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/config
      - ./data/web:/etc/ssl/web
    networks:
      - speedtest-tracker
      - frontend
    restart: unless-stopped
    depends_on:
      - db
    labels:
      traefik.enable: true
      traefik.http.routers.speedtest-tracker.entryPoints: websecure
      traefik.http.routers.speedtest-tracker.rule: Host(`speedtest.hoebergen.net`)
      traefik.http.services.speedtest-tracker.loadbalancer.server.port: 80
      traefik.http.routers.speedtest-tracker.middlewares: localAccess@file
  db:
    container_name: speedtest-tracker-db
    image: mariadb:10
    restart: always
    networks:
      - speedtest-tracker
    environment:
      - MARIADB_DATABASE=speedtest_tracker
      - MARIADB_USER=jordy
      - MARIADB_PASSWORD=SUPERSECUREPASSWORDBYERWINGROEPPA
      - MARIADB_RANDOM_ROOT_PASSWORD=true
    volumes:
      - ./db:/var/lib/mysql
networks:
  speedtest-tracker:
  frontend:
    external: true
