model_list:
#  - model_name: DeepSeek-V3.2
#    litellm_params:
#      model: azure/DeepSeek-V3.2                   
#      api_base: os.environ/AZURE_API_BASE
#      api_key: os.environ/AZURE_API_KEY
#      api_version: 2024-05-01-preview     

        
litellm_settings:
  timeout: 600
  num_retries: 3
  json_logs: true

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY       # must start with "sk-"
  database_url: os.environ/DATABASE_URL           # Postgres
  ui_access_mode: admin_only
  json_logs: true

router_settings:
  routing_strategy: usage-based-routing-v2
  num_retries: 3
  allowed_fails: 3
  cooldown_time: 30
  default_fallbacks:
    - gpt-oss-120b
  redis_host: os.environ/REDIS_HOST
  redis_port: os.environ/REDIS_PORT
  redis_password: os.environ/REDIS_PASSWORD

key_generation_settings:
  default_settings:
    rpm_limit: 300
    tpm_limit: 200000