services:
  traefik:
    container_name: traefik
    image: traefik:v3.4.4
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - ./data/fileConfig.yml:/etc/traefik/fileConfig.yml
      - ./data/traefik.yml:/etc/traefik/traefik.yml
    networks:
      - frontend
    labels:
      traefik.http.routers.api.rule: Host(`traefik.lab-vps-01.hoebergen.net`)
      traefik.http.routers.api.entryPoints: websecure
      traefik.http.routers.api.service: api@internal
      traefik.http.routers.api.middlewares: localAccess@file
      traefik.enable: true
    env_file:
      - ./.env
    restart: unless-stopped

networks:
  frontend:
    driver: bridge
    external: true