services:
  traefik:
    container_name: traefik
    image: traefik:v3.3.6
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - /home/jordy/docker/traefik/data/:/etc/traefik/
      - /home/jordy/docker/traefik/logs/:/var/log/traefik/
    networks:
      - frontend
    labels:
      traefik.http.routers.api.rule: Host(`traefik.lab-vps-01.hoebergen.net`)
      traefik.http.routers.api.entryPoints: websecure
      traefik.http.routers.api.service: api@internal
      traefik.http.routers.api.middlewares: localAccess@file
      traefik.enable: true
    env_file:
      - ./.env
    restart: unless-stopped

networks:
  frontend:
    driver: bridge
    external: true
