services:
  adguardhome-sync:
    image: ghcr.io/bakito/adguardhome-sync:alpine-v0.7.3
    container_name: adguardhome-sync
    command: run
    environment:
      - FEATURES_DNS_SERVER_CONFIG=false
      - CRON=*/30 * * * *
      - RUN_ON_START=true
      - API_DARK_MODE=true
      - API_METRICS_ENABLED=false
      - ORIGIN_URL=${ORIGIN_URL}
      - ORIGIN_WEB_URL=${ORIGIN_WEB_URL}
      - ORIGIN_USERNAME=${USERNAME}
      - ORIGIN_PASSWORD=${PASSWORD}
      - REPLICA1_URL=${REPLICA1_URL}
      - REPLICA1_WEB_URL=${REPLICA1_WEB_URL}
      - REPLICA1_USERNAME=${USERNAME}
      - REPLICA1_PASSWORD=${PASSWORD}
      - API_PORT=8080
      - API_USERNAME=${USERNAME}
      - API_PASSWORD=${PASSWORD}
    ports:
      - 10.0.10.21:8080:8080
    restart: unless-stopped