# without github actions
services:
  immich-server:
    container_name: immich-server
    image: altran1502/immich-server:v1.132.0
    group_add:
      - "109"
    extends:
      file: hwaccel.transcoding.yml
      service: quicksync
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ./.env
    depends_on:
      - redis
      - database
    labels:
      traefik.enable: true
      traefik.http.routers.immich.entryPoints: websecure
      traefik.http.services.immich.loadbalancer.server.port: 2283
      traefik.http.routers.immich.rule: Host(`photos.hoebergen.net`)
      # traefik.http.routers.api.middlewares: localAccess@file
      # Allow access via private tunnel
    restart: always
    networks:
      - immich
      - frontend

  immich-machine-learning:
    container_name: immich-machine-learning
    image: altran1502/immich-machine-learning:v1.132.0
    env_file:
      - ./.env
    volumes:
      - model-cache:/cache
    restart: always
    networks:
      - immich
    healthcheck:
      interval: 5m

  redis:
    container_name: immich-redis
    image: valkey/valkey:8-bookworm@sha256:c855f98e09d558a0d7cc1a4e56473231206a4c54c0114ada9c485b47aeb92ec8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - immich

  database:
    container_name: immich-postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    env_file:
      - ./.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: --data-checksums
    volumes:
      - /mnt/media/immich/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always
    networks:
      - immich

  power-tools:
    container_name: immich-power-tools
    image: ghcr.io/varun-raj/immich-power-tools:0.15.0
    env_file:
      - ./.env
    labels:
      traefik.enable: true
      traefik.http.routers.immich-power-tools.entryPoints: websecure
      traefik.http.services.immich-power-tools.loadbalancer.server.port: 3000
      traefik.http.routers.immich-power-tools.rule: Host(`tools.photos.hoebergen.net`)
      traefik.http.routers.api.middlewares: localAccess@file
    restart: always
    networks:
      - immich
      - frontend

networks:
  frontend:
    name: frontend
    external: true
  immich:
    name: immich
    external: true
volumes:
  model-cache:
