services:
  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    env_file: .env
    expose:
      - "3000"
    volumes:
      - /docker/outline/config:/var/lib/outline/data
    depends_on:
      - postgres
      - redis
    networks:
      - backend-outline
      - pangolin

  redis:
    image: redis
    env_file: .env
    expose:
      - "6379"
    volumes:
      - /docker/outline/redis/redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3
    networks:
      - backend-outline

  postgres:
    image: postgres:18
    env_file: .env
    expose:
      - "5432"
    volumes:
      - /docker/outline/database:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "outline", "-U", "user"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_DB: 'outline'
    networks:
      - backend-outline

networks:
  pangolin:
    external: true
  backend-outline:
