services:
  metube:
    image: alexta69/metube:2026.08.20
    container_name: metube
    restart: unless-stopped
    volumes:
      - /docker/metube/downloads:/downloads
    labels:
      traefik.enable: true
      traefik.http.routers.metube.entryPoints: websecure
      traefik.http.routers.metube.rule: Host(`yt.hoebergen.net`)
      traefik.http.routers.metube.middlewares: localAccess@file

    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.10'
          memory: 128M
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    environment:
      - TZ=Europe/Amsterdam
networks:
  default:
    name: frontend
    external: true
