services:
  grafana:
    image: grafana/grafana-enterprise:13.2.0
    container_name: grafana
    restart: unless-stopped
    user: '0'
    labels:
      traefik.enable: true
      traefik.http.routers.grafana.entryPoints: websecure
      traefik.http.services.grafana.loadbalancer.server.port: 3000
      traefik.http.routers.grafana.rule: Host(`grafana.hoebergen.net`)
    volumes:
      - /docker/grafana/data:/var/lib/grafana
    env_file: .env

    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.10'
          memory: 128M
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    environment:
      - TZ=Europe/Amsterdam
networks:
  default:
    name: frontend
    external: true
