services:
  grafana:
    image: grafana/grafana-enterprise:13.1.3
    container_name: grafana
    restart: unless-stopped
    user: 1000
    labels:
      traefik.enable: true
      traefik.http.routers.grafana.entryPoints: websecure
      traefik.http.services.grafana.loadbalancer.server.port: 3000
      traefik.http.routers.grafana.rule: Host(`grafana.hoebergen.net`)
    volumes:
      - /docker/grafana/data:/var/lib/grafana
    env_file: .env

networks:
  default:
    name: frontend
    external: true
