services:
  pingvin-share:
    container_name: pingvin-share
    image: stonith404/pingvin-share:v1.13.0
    restart: unless-stopped
    environment:
      - TRUST_PROXY=true
    volumes:
      - "/home/jordy/docker/pingvin-share:/opt/app/backend/data"
      - "/home/jordy/docker/pingvin-share:/opt/app/frontend/public/img"
    labels:
      traefik.enable: true
      traefik.http.routers.pingvin-share.entryPoints: websecure
      traefik.http.services.pingvin-share.loadbalancer.server.port: 3000
      traefik.http.routers.pingvin-share.rule: Host(`share.hoebergen.net`)
      # Cloudflare
      dockflare.enable: true
      dockflare.hostname: "share.hoebergen.net"
      dockflare.originsrvname: "share.hoebergen.net"
      dockflare.service: "https://localhost:443"

networks:
  default:
    name: frontend
    external: true