services:
  pingvin-share:
    container_name: pingvin-share
    image: stonith404/pingvin-share:v1.12.0
    restart: unless-stopped
    environment:
      - TRUST_PROXY=true
    volumes:
      - "/home/jordy/docker/pingvin-share:/opt/app/backend/data"
      - "/home/jordy/docker/pingvin-share:/opt/app/frontend/public/img"
      - "./config/config.yaml:/opt/app/config.yaml"
    labels:
      traefik.enable: true
      traefik.http.routers.pingvin-share.entryPoints: websecure
      traefik.http.services.pingvin-share.loadbalancer.server.port: 3000
      traefik.http.routers.pingvin-share.rule: Host(`share.hoebergen.net`)
      # Cloudflare
      cloudflare.tunnel.enable: true
      cloudflare.tunnel.hostname: "share.hoebergen.net"
      cloudflare.tunnel.service: "https://localhost:443"
      cloudflare.tunnel.no_tls_verify: true

networks:
  default:
    name: frontend
    external: true