services:
  bookstack:
    image: lscr.io/linuxserver/bookstack:25.02.20250309
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL="https://docs.hoebergen.net"
      - DB_HOST=bookstack-db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASS=${DB_PASS}
      - DB_DATABASE=bookstackapp
      - STORAGE_TYPE=local
    env_file:
      - .env
    labels:
      # Traefik
      traefik.enable: true
      traefik.http.routers.bookstack.entryPoints: websecure
      traefik.http.services.bookstack.loadbalancer.server.port: 80
      traefik.http.routers.bookstack.rule: Host(`docs.hoebergen.net`)
      # Cloudflare
      cloudflare.tunnel.enable: true
      cloudflare.tunnel.hostname: "docs.hoebergen.net"
      cloudflare.tunnel.service: "https://lab-vps-01:443"
      cloudflare.tunnel.no_tls_verify: true
    volumes:
      - /home/jordy/docker/bookstack/config:/config
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack-db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=Europe/Amsterdam
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=${DB_PASS}
    volumes:
      - /home/jordy/docker/bookstack/data:/config
    restart: unless-stopped

networks:
  default:
    name: frontend
    external: true