services:
  grafana-alloy:
    image: grafana/alloy:v1.19.2
    container_name: grafana-alloy
    restart: unless-stopped
    command:
      - run
      - /etc/alloy/config.alloy
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
    volumes:
      - ./config/config.alloy:/etc/alloy/config.alloy:ro
      - /docker/grafana-alloy/data:/var/lib/alloy/data
    networks:
      - frontend
    labels:
      traefik.enable: true
      traefik.http.routers.alloy.rule: Host(`alloy.lab-vps-01.hoebergen.net`)
      traefik.http.routers.alloy.entryPoints: websecure
      traefik.http.services.alloy.loadbalancer.server.port: 12345
      traefik.http.routers.alloy.middlewares: localAccess@file
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    environment:
      - TZ=Europe/Amsterdam
      - SERVER_NAME=lab-vps-01

volumes:
  alloy-data:
    name: alloy-data

networks:
  frontend:
    external: true
