services:
  newt:
    image: fosrl/newt:1.11.0
    container_name: newt
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DOCKER_SOCKET=http://dockerproxy:2375

networks:
  default:
    name: frontend
    external: true