services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v2.4.0
    container_name: mealie
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - ./data:/app/data/
    environment:
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: Europe/Amsterdam
      BASE_URL: https://recipes.hoebergen.net
    labels:
      traefik.enable: true
      traefik.http.routers.mealie.entryPoints: websecure
      traefik.http.routers.mealie.rule: Host(`recipes.hoebergen.net`)
      traefik.http.routers.mealie.middlewares: localAccess@file

networks:
  default:
    name: frontend
    external: true
