services:
  vaultwarden:
    image: vaultwarden/server:1.33.2-alpine
    container_name: vaultwarden
    volumes:
      - /home/jordy/docker/vaultwarden/data/:/data/
    restart: unless-stopped
    environment:
      PUSH_ENABLED: true
      PUSH_INSTALLATION_ID: ${PUSH_INSTALLATION_ID}
      PUSH_INSTALLATION_KEY: ${PUSH_INSTALLATION_KEY}
      PUSH_RELAY_URI: https://api.bitwarden.eu
      PUSH_IDENTITY_URI: https://identity.bitwarden.eu
      TZ: Europe/Amsterdam
      # ICON_SERVICE: duckduckgo
      HTTP_REQUEST_BLOCK_NON_GLOBAL_IPS: false
      LOG_FILE: /logs/vaultwarden.log
      EXPERIMENTAL_CLIENT_FEATURE_FLAGS: ${EXPERIMENTAL_CLIENT_FEATURE_FLAGS}
      ADMIN_TOKEN: ${VAULTWARDEN_ADMIN_TOKEN}
    labels:
      traefik.enable: true
      # Web UI
      traefik.http.routers.vaultwarden.entryPoints: websecure
      traefik.http.routers.vaultwarden.service: vaultwarden
      traefik.http.services.vaultwarden.loadbalancer.server.port: 80
      traefik.http.routers.vaultwarden.rule: Host(`vault.hoebergen.net`)
      # Admin dashboard
      traefik.http.routers.vaultwarden-admin.rule: Host(`vault.hoebergen.net`) && PathPrefix(`/admin`)
      traefik.http.routers.vaultwarden-admin.entryPoints: websecure
      traefik.http.routers.vaultwarden-admin.middlewares: localAccess@file

networks:
  default:
    name: frontend
    external: true
