services:
  vaultwarden:
    image: vaultwarden/server:1.33.2-alpine
    container_name: vaultwarden
    volumes:
      - /docker/vaultwarden/data/:/data/
    restart: unless-stopped
    environment:
      PUSH_ENABLED: true
      PUSH_INSTALLATION_ID: ${PUSH_INSTALLATION_ID}
      PUSH_INSTALLATION_KEY: ${PUSH_INSTALLATION_KEY}
      PUSH_RELAY_URI: https://api.bitwarden.eu
      PUSH_IDENTITY_URI: https://identity.bitwarden.eu
      TZ: Europe/Amsterdam
      HTTP_REQUEST_BLOCK_NON_GLOBAL_IPS: false
      EXPERIMENTAL_CLIENT_FEATURE_FLAGS: ${EXPERIMENTAL_CLIENT_FEATURE_FLAGS}
      ADMIN_TOKEN: ${VAULTWARDEN_ADMIN_TOKEN}
    labels:
      traefik.enable: true
      # Web UI
      traefik.http.routers.vaultwarden.entryPoints: websecure
      traefik.http.routers.vaultwarden.service: vaultwarden
      traefik.http.services.vaultwarden.loadbalancer.server.port: 80
      traefik.http.routers.vaultwarden.rule: Host(`vault.hoebergen.net`)
      # Admin dashboard
      traefik.http.routers.vaultwarden-admin.rule: Host(`vault.hoebergen.net`) && PathPrefix(`/admin`)
      traefik.http.routers.vaultwarden-admin.entryPoints: websecure
      traefik.http.routers.vaultwarden-admin.middlewares: localAccess@file
      # Cloudflare
      cloudflare.tunnel.enable: true
      cloudflare.tunnel.hostname: "vault.hoebergen.net"
      cloudflare.tunnel.service: "https://lab-vps-01:443"
      cloudflare.tunnel.no_tls_verify: true

  vaultwarden-backup:
    image: ttionya/vaultwarden-backup:1.24.3
    restart: always
    environment:
      RCLONE_REMOTE_NAME: 'BitwardenBackup'
      RCLONE_REMOTE_DIR: '/Backups/Bitwarden/'
      RCLONE_GLOBAL_FLAG: ''
      CRON: '0 */12 * * *'
      ZIP_ENABLE: 'TRUE'
      ZIP_PASSWORD: '${BACKUP_ZIP_PASSWORD}'
      ZIP_TYPE: '7z'
      BACKUP_FILE_SUFFIX: '%Y%m%d'
      BACKUP_KEEP_DAYS: 14
      TIMEZONE: 'CET'
    volumes:
      - /docker/vaultwarden/data/:/bitwarden/data/
      - vaultwarden-rclone-data:/config

networks:
  default:
    name: frontend
    external: true

volumes:
  vaultwarden-rclone-data:
    external: true
    name: vaultwarden-rclone-data
