services:
  vaultwarden:
    image: vaultwarden/server:1.32.1-alpine
    container_name: vaultwarden
    volumes:
      - ./data/:/data/
      - ./logs/:/logs/
    restart: unless-stopped
    environment:
      PUSH_ENABLED: true
      PUSH_INSTALLATION_ID: ${PUSH_INSTALLATION_ID}
      PUSH_INSTALLATION_KEY: ${PUSH_INSTALLATION_KEY}
      PUSH_RELAY_URI: https://api.bitwarden.eu
      PUSH_IDENTITY_URI: https://identity.bitwarden.eu
      TZ: Europe/Amsterdam
      ICON_SERVICE: duckduckgo
      ICON_BLACKLIST_NON_GLOBAL_IPS: false
      LOG_FILE: /logs/vaultwarden.log
      EXPERIMENTAL_CLIENT_FEATURE_FLAGS: fido2-vault-credentials
      ADMIN_TOKEN: ${VAULTWARDEN_ADMIN_TOKEN}
    labels:
      traefik.enable: true
      traefik.http.routers.vaultwarden.entryPoints: https
      traefik.http.routers.vaultwarden.service: vaultwarden
      traefik.http.services.vaultwarden.loadbalancer.server.port: 80
      traefik.http.routers.vaultwarden.rule: Host(`vault.hoebergen.net`)

networks:
  default:
    name: proxy
    external: true
