services:
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:v0.4.1
    container_name: dockerproxy
    environment:
      - CONTAINERS=1 # Allow access to viewing containers
      - POST=0 # Disallow any POST operations (effectively read-only)
    ports:
      - 172.16.2.2:2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    restart: unless-stopped

networks:
  default:
    external: true
    name: frontend