services:
  glance:
    image: glanceapp/glance:v0.8.5
    container_name: glance
    volumes:
      - /docker/glance/config:/app/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    dns:
      - "10.0.10.201"
      - "10.0.10.21"
    labels:
      traefik.enable: true
      traefik.http.routers.glance.entryPoints: websecure
      traefik.http.services.glance.loadbalancer.server.port: 8080
      traefik.http.routers.glance.rule: Host(`home.hoebergen.net`)
      traefik.http.routers.glance.middlewares: localAccess@file
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - TZ=Europe/Amsterdam
networks:
  default:
    name: frontend
    external: true
