services:
  glance:
    image: glanceapp/glance:v0.7.10
    container_name: glance
    volumes:
      - ./config:/app/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.glance.entryPoints: websecure
      traefik.http.services.glance.loadbalancer.server.port: 8080
      traefik.http.routers.glance.rule: Host(`home.hoebergen.net`)
      traefik.http.routers.glance.middlewares: localAccess@file

networks:
  default:
    name: frontend
    external: true
