name: Deploy Docker Compose

on:
    push:
        branches:
            - main
        paths:
            - 'lab*/**'
            - 'str*/**'
            - 'orc*/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Send request to Komodo
        run: |
          curl -X POST "${{ secrets.WEBHOOK_URL }}" \
            -H "Content-Type: application/json" \
            -H "X-Hub-Signature: sha1=$(echo -n \"$GITHUB_EVENT_PAYLOAD\" | openssl dgst -sha1 -hmac \"$WEBHOOK_SECRET\" | sed 's/^.* //')" \
            -d '${{ toJson(github.event) }}'
