services:
  homebox:
    image: ghcr.io/sysadminsmedia/homebox:0.16.0
    container_name: homebox
    restart: always
    environment:
    - HBOX_LOG_LEVEL=info
    - HBOX_LOG_FORMAT=text
    - HBOX_WEB_MAX_UPLOAD_SIZE=50
    volumes:
      - ./data/:/data/
    labels:
      traefik.enable: true
      traefik.http.routers.homebox.entryPoints: websecure
      traefik.http.services.homebox.loadbalancer.server.port: 7745
      traefik.http.routers.homebox.rule: Host(`homebox.hoebergen.net`)
      traefik.http.routers.homebox.middlewares: localAccess@file

networks:
  default:
    name: frontend
    external: true