services:
  immich-diskchecker:
    container_name: immich-diskchecker
    image: alpine:3.22.1
    network_mode: none
    volumes:
      - ${DISK_ROOT}:/mnt/externaldisk:ro
    command:
      - "/bin/sh"
      - "-c"
      - "[ -f /mnt/externaldisk/.883f4828-a568-40c6-b21e-dc3b93c2aedd ]"

  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:v1.141.1
    group_add:
      - "109"
    extends:
      file: hwaccel.transcoding.yml
      service: quicksync
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ./.env
    depends_on:
      redis:
        condition: service_healthy
      database:
        condition: service_healthy
      immich-diskchecker:
        condition: service_completed_successfully
        restart: true
    labels:
      traefik.enable: true
      traefik.http.routers.immich.entryPoints: websecure
      traefik.http.services.immich.loadbalancer.server.port: 2283
      traefik.http.routers.immich.rule: Host(`photos.hoebergen.net`)
      #traefik.http.routers.immich.middlewares: localAccess@file
    restart: always
    networks:
      - immich
      - frontend

  immich-machine-learning:
    container_name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:v1.141.1
    env_file:
      - ./.env
    volumes:
      - model-cache:/cache
    restart: always
    networks:
      - immich
    healthcheck:
      interval: 5m

  redis:
    container_name: immich-redis
    image: valkey/valkey:8-bookworm@sha256:fea8b3e67b15729d4bb70589eb03367bab9ad1ee89c876f54327fc7c6e618571
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - immich

  database:
    container_name: immich-postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:c44be5f2871c59362966d71eab4268170eb6f5653c0e6170184e72b38ffdf107
    env_file:
      - ./.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: --data-checksums
    volumes:
      - ${DATABASE_LOCATION}:/var/lib/postgresql/data
    depends_on:
      immich-diskchecker:
        condition: service_completed_successfully
        restart: true
    restart: always
    networks:
      - immich

  power-tools:
    container_name: immich-power-tools
    image: ghcr.io/varun-raj/immich-power-tools:0.18.0
    env_file:
      - ./.env
    labels:
      traefik.enable: true
      traefik.http.routers.immich-power-tools.entryPoints: websecure
      traefik.http.services.immich-power-tools.loadbalancer.server.port: 3000
      traefik.http.routers.immich-power-tools.rule: Host(`tools.photos.hoebergen.net`)
      traefik.http.routers.immich-power-tools.tls.certresolver: letsencrypt
      traefik.http.routers.immich-power-tools.middlewares: localAccess@file
    restart: always
    networks:
      - immich
      - frontend

networks:
  frontend:
    name: frontend
    external: true
  immich:
    name: backend-immich

volumes:
  model-cache: