services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.10.8
    container_name: homepage
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./images:/app/public/images
      - ./icons:/app/public/icons
    env_file:
      - ./.env
    environment:
      PUID: 1000
      PGID: 1000