services:
  influxdb:
    image: influxdb:3.11.2-core
    container_name: influxdb
    restart: unless-stopped
    command:
      - influxdb3
      - serve
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3/data
      - --plugin-dir=/var/lib/influxdb3/plugins
      - --http-bind=0.0.0.0:8086
    volumes:
      - /docker/influxdb3/data:/var/lib/influxdb3/data
      - /docker/influxdb3/plugins:/var/lib/influxdb3/plugins
    networks:
      - frontend
    labels:
      traefik.enable: true
      traefik.http.routers.influxdb.rule: Host(`influxdb.str-vps-01.hoebergen.net`)
      traefik.http.routers.influxdb.entryPoints: websecure
      traefik.http.services.influxdb.loadbalancer.server.port: 8086

networks:
  frontend:
    external: true
